# DataSource Config
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    static-path-pattern: /static/**
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    #设置空如何序列化
    defaultPropertyInclusion: non_null
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3308/pic_cut?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  servlet:
    context-path: /picCut
    session:
      timeout: 36000
  port: 9092
  tomcat:
    max-http-form-post-size: 104857600